function PP_plotSnapshot(handles)
  % call plotSnapshot() using parameters from the handles structure
  
  if handles.surface == 1
    MainPlotType = 'surface';
  else
    MainPlotType = 'contour';
  end
  
  if ~isfield(handles, 'geofile')
    handles.geofile = '';
  end
  if ~isfield(handles, 'inpfile')
    handles.inpfile = '';
  end
  
  % TODO: 2017-02-28: Implement data+epsilon contour plotting from PP GUI.
  plotSnapshot('filename', handles.snapfile,...
               'column', handles.col,...
               'zlimits', [ handles.minplotvalue, handles.maxplotvalue ],...
               'swap_axes', false,...
               'view', 2,...
               'createFigure', true,...
               'hide_figures', false,...
               'saveas', handles.autosave,...
               'contourFile', '',...
               'contourColumn', 3,...
               'contourValues', NaN,...
               'LineColor', 'yellow',...
               'modulus', logical(handles.modulus),...
               'normalized', false,...
               'log10', false,...
               'symmetricRange', logical(handles.symmetricRange),...
               'updateCaxis', true,...
               'drawGeometry', logical(handles.geometry),...
               'geofile', handles.geofile,...
               'inpfile', handles.inpfile,...
               'MainPlotType', MainPlotType,...
               'MainContourZposition', 0,...
               'pre_2008_BFDTD_version', handles.pre_2008_BFDTD_version,...
               'handles', handles);
              
end
