function data_info = mpb_DataInfo_FCC(varargin)
  p = inputParser();
  p = inputParserWrapper(p, 'addParamValue', 'v1', [0, 0, 1], @isnumeric);
  p = inputParserWrapper(p, 'addParamValue', 'v2', [0, 1, 0], @isnumeric);
  p = inputParserWrapper(p, 'parse', varargin{:});

  data_info = mpb_DataInfo('a', 1, ...
                           'a1', 1/2*[0,1,1], ...
                           'a2', 1/2*[1,0,1], ...
                           'a3', 1/2*[1,1,0], ...
                           'v1', p.Results.v1, ...
                           'v2', p.Results.v2);
end
