# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'bfdtd_tool.ui'
#
# Created: Tue Jun 10 15:41:06 2014
#      by: PyQt5 UI code generator 5.2.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(909, 881)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.scrollArea = QtWidgets.QScrollArea(self.centralwidget)
        self.scrollArea.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.scrollArea.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 887, 810))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.tabWidget = QtWidgets.QTabWidget(self.scrollAreaWidgetContents)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.tab)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.listWidget_InputFiles = QtWidgets.QListWidget(self.tab)
        self.listWidget_InputFiles.setSelectionMode(QtWidgets.QAbstractItemView.ExtendedSelection)
        self.listWidget_InputFiles.setSelectionRectVisible(True)
        self.listWidget_InputFiles.setObjectName("listWidget_InputFiles")
        self.verticalLayout_4.addWidget(self.listWidget_InputFiles)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.pushButton_addInputFiles = QtWidgets.QPushButton(self.tab)
        self.pushButton_addInputFiles.setObjectName("pushButton_addInputFiles")
        self.horizontalLayout_6.addWidget(self.pushButton_addInputFiles)
        self.checkBox_DirectLoad = QtWidgets.QCheckBox(self.tab)
        self.checkBox_DirectLoad.setObjectName("checkBox_DirectLoad")
        self.horizontalLayout_6.addWidget(self.checkBox_DirectLoad)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem)
        self.verticalLayout_4.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.pushButton_removeInputFiles = QtWidgets.QPushButton(self.tab)
        self.pushButton_removeInputFiles.setObjectName("pushButton_removeInputFiles")
        self.horizontalLayout_9.addWidget(self.pushButton_removeInputFiles)
        self.pushButton_moveInputFileUp = QtWidgets.QPushButton(self.tab)
        self.pushButton_moveInputFileUp.setObjectName("pushButton_moveInputFileUp")
        self.horizontalLayout_9.addWidget(self.pushButton_moveInputFileUp)
        self.pushButton_moveInputFileDown = QtWidgets.QPushButton(self.tab)
        self.pushButton_moveInputFileDown.setObjectName("pushButton_moveInputFileDown")
        self.horizontalLayout_9.addWidget(self.pushButton_moveInputFileDown)
        self.pushButton_clearList = QtWidgets.QPushButton(self.tab)
        self.pushButton_clearList.setObjectName("pushButton_clearList")
        self.horizontalLayout_9.addWidget(self.pushButton_clearList)
        self.verticalLayout_4.addLayout(self.horizontalLayout_9)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.pushButton_loadInputFiles = QtWidgets.QPushButton(self.tab)
        self.pushButton_loadInputFiles.setObjectName("pushButton_loadInputFiles")
        self.horizontalLayout_10.addWidget(self.pushButton_loadInputFiles)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem1)
        self.verticalLayout_4.addLayout(self.horizontalLayout_10)
        self.tabWidget.addTab(self.tab, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.label_15 = QtWidgets.QLabel(self.tab_3)
        self.label_15.setGeometry(QtCore.QRect(460, 40, 161, 17))
        self.label_15.setObjectName("label_15")
        self.label_16 = QtWidgets.QLabel(self.tab_3)
        self.label_16.setGeometry(QtCore.QRect(20, 30, 161, 17))
        self.label_16.setObjectName("label_16")
        self.pushButton_12 = QtWidgets.QPushButton(self.tab_3)
        self.pushButton_12.setGeometry(QtCore.QRect(520, 260, 201, 27))
        self.pushButton_12.setObjectName("pushButton_12")
        self.pushButton_7 = QtWidgets.QPushButton(self.tab_3)
        self.pushButton_7.setGeometry(QtCore.QRect(270, 270, 201, 27))
        self.pushButton_7.setObjectName("pushButton_7")
        self.listView_3 = QtWidgets.QListView(self.tab_3)
        self.listView_3.setGeometry(QtCore.QRect(710, 130, 111, 101))
        self.listView_3.setObjectName("listView_3")
        self.label_13 = QtWidgets.QLabel(self.tab_3)
        self.label_13.setGeometry(QtCore.QRect(20, 310, 101, 17))
        self.label_13.setObjectName("label_13")
        self.label_11 = QtWidgets.QLabel(self.tab_3)
        self.label_11.setGeometry(QtCore.QRect(110, 320, 121, 17))
        self.label_11.setObjectName("label_11")
        self.label_17 = QtWidgets.QLabel(self.tab_3)
        self.label_17.setGeometry(QtCore.QRect(120, 290, 62, 17))
        self.label_17.setObjectName("label_17")
        self.comboBox_3 = QtWidgets.QComboBox(self.tab_3)
        self.comboBox_3.setGeometry(QtCore.QRect(290, 330, 87, 29))
        self.comboBox_3.setObjectName("comboBox_3")
        self.tableWidget = QtWidgets.QTableWidget(self.tab_3)
        self.tableWidget.setGeometry(QtCore.QRect(60, 60, 351, 192))
        self.tableWidget.setAcceptDrops(True)
        self.tableWidget.setDragEnabled(True)
        self.tableWidget.setDragDropOverwriteMode(False)
        self.tableWidget.setDragDropMode(QtWidgets.QAbstractItemView.InternalMove)
        self.tableWidget.setDefaultDropAction(QtCore.Qt.IgnoreAction)
        self.tableWidget.setSelectionMode(QtWidgets.QAbstractItemView.MultiSelection)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(3)
        self.tableWidget.setRowCount(5)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(0, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(0, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(1, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(1, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(1, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(2, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(2, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(2, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(3, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(3, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(3, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(4, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(4, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(4, 2, item)
        self.listWidget = QtWidgets.QListWidget(self.tab_3)
        self.listWidget.setGeometry(QtCore.QRect(430, 70, 256, 161))
        self.listWidget.setDragEnabled(True)
        self.listWidget.setDragDropMode(QtWidgets.QAbstractItemView.InternalMove)
        self.listWidget.setObjectName("listWidget")
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        self.tabWidget.addTab(self.tab_3, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.tab_4)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.tableWidget_Frequencies = QtWidgets.QTableWidget(self.tab_4)
        self.tableWidget_Frequencies.setDragEnabled(True)
        self.tableWidget_Frequencies.setDragDropOverwriteMode(False)
        self.tableWidget_Frequencies.setDragDropMode(QtWidgets.QAbstractItemView.DragOnly)
        self.tableWidget_Frequencies.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tableWidget_Frequencies.setObjectName("tableWidget_Frequencies")
        self.tableWidget_Frequencies.setColumnCount(3)
        self.tableWidget_Frequencies.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_Frequencies.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_Frequencies.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_Frequencies.setHorizontalHeaderItem(2, item)
        self.tableWidget_Frequencies.horizontalHeader().setDefaultSectionSize(150)
        self.tableWidget_Frequencies.horizontalHeader().setStretchLastSection(True)
        self.horizontalLayout_7.addWidget(self.tableWidget_Frequencies)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.pushButton_AddFrequency = QtWidgets.QPushButton(self.tab_4)
        self.pushButton_AddFrequency.setObjectName("pushButton_AddFrequency")
        self.verticalLayout.addWidget(self.pushButton_AddFrequency)
        self.pushButton_AddFrequencyFromFrequencyList = QtWidgets.QPushButton(self.tab_4)
        self.pushButton_AddFrequencyFromFrequencyList.setObjectName("pushButton_AddFrequencyFromFrequencyList")
        self.verticalLayout.addWidget(self.pushButton_AddFrequencyFromFrequencyList)
        self.pushButton_AddFrequencyFromInpFile = QtWidgets.QPushButton(self.tab_4)
        self.pushButton_AddFrequencyFromInpFile.setObjectName("pushButton_AddFrequencyFromInpFile")
        self.verticalLayout.addWidget(self.pushButton_AddFrequencyFromInpFile)
        self.pushButton_RemoveFrequency = QtWidgets.QPushButton(self.tab_4)
        self.pushButton_RemoveFrequency.setObjectName("pushButton_RemoveFrequency")
        self.verticalLayout.addWidget(self.pushButton_RemoveFrequency)
        self.pushButton_moveFrequencyUp = QtWidgets.QPushButton(self.tab_4)
        self.pushButton_moveFrequencyUp.setObjectName("pushButton_moveFrequencyUp")
        self.verticalLayout.addWidget(self.pushButton_moveFrequencyUp)
        self.pushButton_moveFrequencyDown = QtWidgets.QPushButton(self.tab_4)
        self.pushButton_moveFrequencyDown.setObjectName("pushButton_moveFrequencyDown")
        self.verticalLayout.addWidget(self.pushButton_moveFrequencyDown)
        self.pushButton_clearFrequencyList = QtWidgets.QPushButton(self.tab_4)
        self.pushButton_clearFrequencyList.setObjectName("pushButton_clearFrequencyList")
        self.verticalLayout.addWidget(self.pushButton_clearFrequencyList)
        self.horizontalLayout_7.addLayout(self.verticalLayout)
        self.verticalLayout_5.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.formLayout_3 = QtWidgets.QFormLayout()
        self.formLayout_3.setObjectName("formLayout_3")
        self.label_8 = QtWidgets.QLabel(self.tab_4)
        self.label_8.setObjectName("label_8")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_8)
        self.spinBox_StartingSample = QtWidgets.QSpinBox(self.tab_4)
        self.spinBox_StartingSample.setMinimum(1)
        self.spinBox_StartingSample.setMaximum(100000000)
        self.spinBox_StartingSample.setObjectName("spinBox_StartingSample")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.spinBox_StartingSample)
        self.label_9 = QtWidgets.QLabel(self.tab_4)
        self.label_9.setObjectName("label_9")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_9)
        self.spinBox_First = QtWidgets.QSpinBox(self.tab_4)
        self.spinBox_First.setMinimum(1)
        self.spinBox_First.setMaximum(100000000)
        self.spinBox_First.setObjectName("spinBox_First")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.spinBox_First)
        self.label_10 = QtWidgets.QLabel(self.tab_4)
        self.label_10.setObjectName("label_10")
        self.formLayout_3.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_10)
        self.spinBox_Repetition = QtWidgets.QSpinBox(self.tab_4)
        self.spinBox_Repetition.setMinimum(1)
        self.spinBox_Repetition.setMaximum(100000000)
        self.spinBox_Repetition.setObjectName("spinBox_Repetition")
        self.formLayout_3.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.spinBox_Repetition)
        self.horizontalLayout_11.addLayout(self.formLayout_3)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem2)
        self.verticalLayout_5.addLayout(self.horizontalLayout_11)
        self.tabWidget.addTab(self.tab_4, "")
        self.tab_5 = QtWidgets.QWidget()
        self.tab_5.setObjectName("tab_5")
        self.tabWidget.addTab(self.tab_5, "")
        self.verticalLayout_2.addWidget(self.tabWidget)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_2 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.lineEdit_OutputDirectory = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.lineEdit_OutputDirectory.setObjectName("lineEdit_OutputDirectory")
        self.horizontalLayout.addWidget(self.lineEdit_OutputDirectory)
        self.pushButton_SelectOutputDirectory = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.pushButton_SelectOutputDirectory.setObjectName("pushButton_SelectOutputDirectory")
        self.horizontalLayout.addWidget(self.pushButton_SelectOutputDirectory)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_3 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_2.addWidget(self.label_3)
        self.lineEdit_BaseName = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.lineEdit_BaseName.setObjectName("lineEdit_BaseName")
        self.horizontalLayout_2.addWidget(self.lineEdit_BaseName)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_5 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_3.addWidget(self.label_5)
        self.comboBox_Operation = QtWidgets.QComboBox(self.scrollAreaWidgetContents)
        self.comboBox_Operation.setObjectName("comboBox_Operation")
        self.comboBox_Operation.addItem("")
        self.comboBox_Operation.addItem("")
        self.comboBox_Operation.addItem("")
        self.comboBox_Operation.addItem("")
        self.horizontalLayout_3.addWidget(self.comboBox_Operation)
        self.pushButton_Run = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.pushButton_Run.setObjectName("pushButton_Run")
        self.horizontalLayout_3.addWidget(self.pushButton_Run)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.checkBox_removeProbes = QtWidgets.QCheckBox(self.scrollAreaWidgetContents)
        self.checkBox_removeProbes.setObjectName("checkBox_removeProbes")
        self.gridLayout.addWidget(self.checkBox_removeProbes, 0, 0, 1, 1)
        self.checkBox_removeTimeAndEpsilonSnapshots = QtWidgets.QCheckBox(self.scrollAreaWidgetContents)
        self.checkBox_removeTimeAndEpsilonSnapshots.setObjectName("checkBox_removeTimeAndEpsilonSnapshots")
        self.gridLayout.addWidget(self.checkBox_removeTimeAndEpsilonSnapshots, 0, 1, 2, 1)
        self.checkBox_removeFrequencySnapshots = QtWidgets.QCheckBox(self.scrollAreaWidgetContents)
        self.checkBox_removeFrequencySnapshots.setObjectName("checkBox_removeFrequencySnapshots")
        self.gridLayout.addWidget(self.checkBox_removeFrequencySnapshots, 0, 2, 2, 1)
        self.checkBox_removeGeometryObjects = QtWidgets.QCheckBox(self.scrollAreaWidgetContents)
        self.checkBox_removeGeometryObjects.setObjectName("checkBox_removeGeometryObjects")
        self.gridLayout.addWidget(self.checkBox_removeGeometryObjects, 1, 0, 2, 1)
        self.checkBox_clearFileList = QtWidgets.QCheckBox(self.scrollAreaWidgetContents)
        self.checkBox_clearFileList.setChecked(True)
        self.checkBox_clearFileList.setObjectName("checkBox_clearFileList")
        self.gridLayout.addWidget(self.checkBox_clearFileList, 2, 2, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.groupBox = QtWidgets.QGroupBox(self.scrollAreaWidgetContents)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.radioButton_ArbitraryLocation = QtWidgets.QRadioButton(self.groupBox)
        self.radioButton_ArbitraryLocation.setObjectName("radioButton_ArbitraryLocation")
        self.horizontalLayout_5.addWidget(self.radioButton_ArbitraryLocation)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.radioButton_ObjectLocation = QtWidgets.QRadioButton(self.groupBox)
        self.radioButton_ObjectLocation.setObjectName("radioButton_ObjectLocation")
        self.horizontalLayout_4.addWidget(self.radioButton_ObjectLocation)
        self.comboBox_ObjectLocation = QtWidgets.QComboBox(self.groupBox)
        self.comboBox_ObjectLocation.setObjectName("comboBox_ObjectLocation")
        self.horizontalLayout_4.addWidget(self.comboBox_ObjectLocation)
        self.horizontalLayout_5.addLayout(self.horizontalLayout_4)
        self.verticalLayout_3.addLayout(self.horizontalLayout_5)
        self.formLayout_2 = QtWidgets.QFormLayout()
        self.formLayout_2.setObjectName("formLayout_2")
        self.label_19 = QtWidgets.QLabel(self.groupBox)
        self.label_19.setObjectName("label_19")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_19)
        self.lineEdit_X = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_X.setObjectName("lineEdit_X")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.lineEdit_X)
        self.label_20 = QtWidgets.QLabel(self.groupBox)
        self.label_20.setObjectName("label_20")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_20)
        self.lineEdit_Y = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_Y.setObjectName("lineEdit_Y")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.lineEdit_Y)
        self.label_21 = QtWidgets.QLabel(self.groupBox)
        self.label_21.setObjectName("label_21")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_21)
        self.lineEdit_Z = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_Z.setObjectName("lineEdit_Z")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.lineEdit_Z)
        self.verticalLayout_3.addLayout(self.formLayout_2)
        self.horizontalLayout_8.addWidget(self.groupBox)
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.label_18 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_18.setObjectName("label_18")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_18)
        self.lineEdit_Ncells = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.lineEdit_Ncells.setEnabled(True)
        self.lineEdit_Ncells.setText("")
        self.lineEdit_Ncells.setReadOnly(True)
        self.lineEdit_Ncells.setObjectName("lineEdit_Ncells")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.lineEdit_Ncells)
        self.label_7 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_7.setObjectName("label_7")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_7)
        self.spinBox_Niterations = QtWidgets.QSpinBox(self.scrollAreaWidgetContents)
        self.spinBox_Niterations.setMinimum(1)
        self.spinBox_Niterations.setMaximum(10000000)
        self.spinBox_Niterations.setSingleStep(1000)
        self.spinBox_Niterations.setObjectName("spinBox_Niterations")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.spinBox_Niterations)
        self.label_4 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.spinBox_Walltime = QtWidgets.QSpinBox(self.scrollAreaWidgetContents)
        self.spinBox_Walltime.setMinimum(1)
        self.spinBox_Walltime.setMaximum(360)
        self.spinBox_Walltime.setObjectName("spinBox_Walltime")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.spinBox_Walltime)
        self.label_6 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_6.setObjectName("label_6")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_6)
        self.comboBox_Executable = QtWidgets.QComboBox(self.scrollAreaWidgetContents)
        self.comboBox_Executable.setEditable(True)
        self.comboBox_Executable.setObjectName("comboBox_Executable")
        self.comboBox_Executable.addItem("")
        self.comboBox_Executable.addItem("")
        self.comboBox_Executable.addItem("")
        self.comboBox_Executable.addItem("")
        self.comboBox_Executable.addItem("")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.comboBox_Executable)
        self.label_14 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_14.setObjectName("label_14")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_14)
        self.spinBox_Verbosity = QtWidgets.QSpinBox(self.scrollAreaWidgetContents)
        self.spinBox_Verbosity.setObjectName("spinBox_Verbosity")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.spinBox_Verbosity)
        self.horizontalLayout_8.addLayout(self.formLayout)
        self.verticalLayout_2.addLayout(self.horizontalLayout_8)
        self.verticalLayout_7.addLayout(self.verticalLayout_2)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout_6.addWidget(self.scrollArea)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 909, 27))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuEdit = QtWidgets.QMenu(self.menubar)
        self.menuEdit.setObjectName("menuEdit")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionPreferences = QtWidgets.QAction(MainWindow)
        self.actionPreferences.setObjectName("actionPreferences")
        self.actionSaveConfigAs = QtWidgets.QAction(MainWindow)
        self.actionSaveConfigAs.setObjectName("actionSaveConfigAs")
        self.actionLoadConfig = QtWidgets.QAction(MainWindow)
        self.actionLoadConfig.setObjectName("actionLoadConfig")
        self.actionSaveConfig = QtWidgets.QAction(MainWindow)
        self.actionSaveConfig.setObjectName("actionSaveConfig")
        self.menuFile.addAction(self.actionSaveConfig)
        self.menuFile.addAction(self.actionSaveConfigAs)
        self.menuFile.addAction(self.actionLoadConfig)
        self.menuEdit.addAction(self.actionPreferences)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuEdit.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        self.comboBox_Executable.setCurrentIndex(2)
        self.pushButton_clearList.clicked.connect(self.listWidget_InputFiles.clear)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "BFDTD tool"))
        self.pushButton_addInputFiles.setText(_translate("MainWindow", "Add input files..."))
        self.checkBox_DirectLoad.setText(_translate("MainWindow", "Direct load"))
        self.pushButton_removeInputFiles.setText(_translate("MainWindow", "Remove selected input files"))
        self.pushButton_moveInputFileUp.setText(_translate("MainWindow", "Move up"))
        self.pushButton_moveInputFileDown.setText(_translate("MainWindow", "Move down"))
        self.pushButton_clearList.setText(_translate("MainWindow", "Clear list"))
        self.pushButton_loadInputFiles.setText(_translate("MainWindow", "Load input files"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Input files"))
        self.label_15.setText(_translate("MainWindow", "Shellscript parameters:"))
        self.label_16.setText(_translate("MainWindow", "Snapshot parameters:"))
        self.pushButton_12.setText(_translate("MainWindow", "Load parameters from file..."))
        self.pushButton_7.setText(_translate("MainWindow", "Load parameters from file..."))
        self.label_13.setText(_translate("MainWindow", "Output:"))
        self.label_11.setText(_translate("MainWindow", "Slicing direction:"))
        self.label_17.setText(_translate("MainWindow", "X:"))
        self.tableWidget.setSortingEnabled(False)
        item = self.tableWidget.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "0"))
        item = self.tableWidget.verticalHeaderItem(1)
        item.setText(_translate("MainWindow", "1"))
        item = self.tableWidget.verticalHeaderItem(2)
        item.setText(_translate("MainWindow", "2"))
        item = self.tableWidget.verticalHeaderItem(3)
        item.setText(_translate("MainWindow", "3"))
        item = self.tableWidget.verticalHeaderItem(4)
        item.setText(_translate("MainWindow", "4"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "a"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "b"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "c"))
        __sortingEnabled = self.tableWidget.isSortingEnabled()
        self.tableWidget.setSortingEnabled(False)
        item = self.tableWidget.item(0, 0)
        item.setText(_translate("MainWindow", "456"))
        item = self.tableWidget.item(0, 1)
        item.setText(_translate("MainWindow", "54"))
        item = self.tableWidget.item(0, 2)
        item.setText(_translate("MainWindow", "456899"))
        item = self.tableWidget.item(1, 0)
        item.setText(_translate("MainWindow", "1"))
        item = self.tableWidget.item(1, 1)
        item.setText(_translate("MainWindow", "24524"))
        item = self.tableWidget.item(1, 2)
        item.setText(_translate("MainWindow", "4689"))
        item = self.tableWidget.item(2, 0)
        item.setText(_translate("MainWindow", "4444"))
        item = self.tableWidget.item(2, 1)
        item.setText(_translate("MainWindow", "1"))
        item = self.tableWidget.item(2, 2)
        item.setText(_translate("MainWindow", "47"))
        item = self.tableWidget.item(3, 0)
        item.setText(_translate("MainWindow", "478"))
        item = self.tableWidget.item(3, 1)
        item.setText(_translate("MainWindow", "45"))
        item = self.tableWidget.item(3, 2)
        item.setText(_translate("MainWindow", "47"))
        item = self.tableWidget.item(4, 0)
        item.setText(_translate("MainWindow", "75896"))
        item = self.tableWidget.item(4, 1)
        item.setText(_translate("MainWindow", "1"))
        item = self.tableWidget.item(4, 2)
        item.setText(_translate("MainWindow", "4777"))
        self.tableWidget.setSortingEnabled(__sortingEnabled)
        __sortingEnabled = self.listWidget.isSortingEnabled()
        self.listWidget.setSortingEnabled(False)
        item = self.listWidget.item(0)
        item.setText(_translate("MainWindow", "gdfg"))
        item = self.listWidget.item(1)
        item.setText(_translate("MainWindow", "hhhhhhhhhh"))
        item = self.listWidget.item(2)
        item.setText(_translate("MainWindow", "bbbbbbbbbb"))
        item = self.listWidget.item(3)
        item.setText(_translate("MainWindow", "asda"))
        item = self.listWidget.item(4)
        item.setText(_translate("MainWindow", "aaaaaaaaaaaa"))
        self.listWidget.setSortingEnabled(__sortingEnabled)
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("MainWindow", "Parameters"))
        self.tableWidget_Frequencies.setSortingEnabled(True)
        item = self.tableWidget_Frequencies.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Frequency (MHz)"))
        item = self.tableWidget_Frequencies.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Wavelength (mum)"))
        item = self.tableWidget_Frequencies.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Comment"))
        self.pushButton_AddFrequency.setText(_translate("MainWindow", "Add frequency"))
        self.pushButton_AddFrequencyFromFrequencyList.setText(_translate("MainWindow", "Add from frequency list file..."))
        self.pushButton_AddFrequencyFromInpFile.setText(_translate("MainWindow", "Add from .inp file..."))
        self.pushButton_RemoveFrequency.setText(_translate("MainWindow", "Remove selected frequencies"))
        self.pushButton_moveFrequencyUp.setText(_translate("MainWindow", "Move up"))
        self.pushButton_moveFrequencyDown.setText(_translate("MainWindow", "Move down"))
        self.pushButton_clearFrequencyList.setText(_translate("MainWindow", "Clear list"))
        self.label_8.setText(_translate("MainWindow", "Starting sample:"))
        self.label_9.setText(_translate("MainWindow", "First:"))
        self.label_10.setText(_translate("MainWindow", "Repetition:"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("MainWindow", "Frequency list"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_5), _translate("MainWindow", "Emitter position"))
        self.label_2.setText(_translate("MainWindow", "Output directory:"))
        self.pushButton_SelectOutputDirectory.setText(_translate("MainWindow", "Select directory..."))
        self.label_3.setText(_translate("MainWindow", "Basename:"))
        self.label_5.setText(_translate("MainWindow", "Operation:"))
        self.comboBox_Operation.setItemText(0, _translate("MainWindow", "Add central snapshots"))
        self.comboBox_Operation.setItemText(1, _translate("MainWindow", "Print number of cells"))
        self.comboBox_Operation.setItemText(2, _translate("MainWindow", "Add mode volume snapshots"))
        self.comboBox_Operation.setItemText(3, _translate("MainWindow", "Convert frequency to epsilon snapshots"))
        self.pushButton_Run.setText(_translate("MainWindow", "Run operation"))
        self.checkBox_removeProbes.setText(_translate("MainWindow", "Remove probes"))
        self.checkBox_removeTimeAndEpsilonSnapshots.setText(_translate("MainWindow", "Remove time and epsilon snapshots"))
        self.checkBox_removeFrequencySnapshots.setText(_translate("MainWindow", "Remove frequency snapshots"))
        self.checkBox_removeGeometryObjects.setText(_translate("MainWindow", "Remove geometry objects"))
        self.checkBox_clearFileList.setText(_translate("MainWindow", "Clear file list (for .in file)"))
        self.groupBox.setTitle(_translate("MainWindow", "Location for Central snapshots and mode volume snapshots:"))
        self.radioButton_ArbitraryLocation.setText(_translate("MainWindow", "Arbitrary location"))
        self.radioButton_ObjectLocation.setText(_translate("MainWindow", "Object location"))
        self.label_19.setText(_translate("MainWindow", "X:"))
        self.lineEdit_X.setText(_translate("MainWindow", "0"))
        self.label_20.setText(_translate("MainWindow", "Y:"))
        self.lineEdit_Y.setText(_translate("MainWindow", "0"))
        self.label_21.setText(_translate("MainWindow", "Z:"))
        self.lineEdit_Z.setText(_translate("MainWindow", "0"))
        self.label_18.setText(_translate("MainWindow", "Number of cells:"))
        self.label_7.setText(_translate("MainWindow", "Iterations:"))
        self.label_4.setText(_translate("MainWindow", "Walltime:"))
        self.label_6.setText(_translate("MainWindow", "Executable:"))
        self.comboBox_Executable.setItemText(0, _translate("MainWindow", "fdtd64_2003"))
        self.comboBox_Executable.setItemText(1, _translate("MainWindow", "fdtd64_2008"))
        self.comboBox_Executable.setItemText(2, _translate("MainWindow", "fdtd64_2013"))
        self.comboBox_Executable.setItemText(3, _translate("MainWindow", "fdtd64_2013_dispersive"))
        self.comboBox_Executable.setItemText(4, _translate("MainWindow", "fdtd64_withRotation"))
        self.label_14.setText(_translate("MainWindow", "Verbosity:"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuEdit.setTitle(_translate("MainWindow", "Settings"))
        self.menuHelp.setTitle(_translate("MainWindow", "Help"))
        self.actionPreferences.setText(_translate("MainWindow", "Preferences..."))
        self.actionSaveConfigAs.setText(_translate("MainWindow", "Save config as..."))
        self.actionLoadConfig.setText(_translate("MainWindow", "Load config..."))
        self.actionSaveConfig.setText(_translate("MainWindow", "Save config"))

