function ret = getBlockStructure(N)
  ret = struct('type', createCell([1,N], 'BLOCK'),...
    'name', createCell([1,N], 'BLOCK'),...
    'lower', createCell([1,N], [-0.5,-0.5,-0.5]),...
    'upper', createCell([1,N], [ 0.5, 0.5, 0.5]),...
    'permittivity', createCell([1,N], 4),...
    'conductivity', createCell([1,N], 0),...
    'center', createCell([1,N], [ 0, 0, 0]));
end
