function ret = getCylinderStructure(N)
  ret = struct('type', createCell([1,N], 'CYLINDER'),...
    'name', createCell([1,N], 'CYLINDER'),...
    'center', createCell([1,N], [0,0,0]),...
    'inner_radius', createCell([1,N], 0),...
    'outer_radius', createCell([1,N], 0.5),...
    'height', createCell([1,N], 1),...
    'permittivity', createCell([1,N], 4),...
    'conductivity', createCell([1,N], 0),...
    'angle', createCell([1,N], 0));
end
