function snapshot = getGenericSnapshotStructure(N)
  snapshot = struct('name', createCell([1,N], 'GENERIC_SNAPSHOT'),...
              'first', createCell([1,N], -1),...
              'repetition', createCell([1,N], -1),...
              'interpolate', createCell([1,N], -1),...
              'real_dft', createCell([1,N], -1),...
              'mod_only', createCell([1,N], -1),...
              'mod_all', createCell([1,N], -1),...
              'plane', createCell([1,N], 1),...
              'P1', [-0.5, -0.5, -0.5],...
              'P2', [ 0.5,  0.5,  0.5],...
              'frequency', createCell([1,N], -1),...
              'starting_sample', createCell([1,N], -1),...
              'E', createCell([1,N], -1),...
              'H', createCell([1,N], -1),...
              'J', createCell([1,N], -1),...
              'power', createCell([1,N], -1),...
              'eps', createCell([1,N], -1),...
              'centro', createCell([1,N], [0,0,0]),...
              'plane_bfdtd_index', createCell([1,N], 1),...
              'plane_letter', createCell([1,N], 'x'),...
              'plane_position', createCell([1,N], 0));
  
end
