function ret = getSphereStructure(N)
  ret = struct('type', createCell([1,N], 'SPHERE'),...
    'name', createCell([1,N], 'SPHERE'),...
    'center', createCell([1,N], [0,0,0]),...
    'outer_radius', createCell([1,N], 0.5),...
    'inner_radius', createCell([1,N], 0),...
    'permittivity', createCell([1,N], 4),...
    'conductivity', createCell([1,N], 0));
end
