function snapshot = getTimeSnapshotStructure(N)
  
  snapshot = struct('name', createCell([1,N], 'TIME_SNAPSHOT'),...
              'first', createCell([1,N], -1),...
              'repetition', createCell([1,N], -1),...
              'plane', createCell([1,N], 1),...
              'P1', [-0.5, -0.5, -0.5],...
              'P2', [ 0.5,  0.5,  0.5],...
              'E', createCell([1,N], -1),...
              'H', createCell([1,N], -1),...
              'J', createCell([1,N], -1),...
              'power', createCell([1,N], -1),...
              'eps', createCell([1,N], -1),...
              'centro', createCell([1,N], [0,0,0]),...
              'plane_bfdtd_index', createCell([1,N], 1),...
              'plane_letter', createCell([1,N], 'x'),...
              'plane_position', createCell([1,N], 0));
  
end
